import pandas as pd
'''
df=pd.DataFrame({'a':[1,2,3,4,5],'b':[6,7,8,9,10],'c':[11,12,13,14,15]})
print(df)
print("Minimum:\n", df.min())
print("Maximum:\n", df.max())
print("Mean:\n", df.mean())
print("Median:\n", df.median())
print("Mode\n:", df.mode())
print("Sum:\n", df.sum())
print("Cummmulative sum:\n", df.cumsum())
print("Variance:\n", df.var())
print("Covariance:\n", df.cov())
print("Standard deviation:\n", df.std())
print("Product:\n", df.prod())
print("Cummulative product:\n", df.cumprod())
print("Count:\n", df.count())
print("Describe function:\n", df.describe())
'''

df=pd.Series([1,2,3,1,4,5,6])
print(df)
print("Minimum:\n", df.min())
print("Maximum:\n", df.max())
print("Mean:\n", df.mean())
print("Median:\n", df.median())
print("Mode:\n", df.mode())
print("Sum:\n", df.sum())
print("Cummmulative sum:\n", df.cumsum())
print("Variance:\n", df.var())
print("Standard deviation:\n", df.std())
print("Product:\n", df.prod())
print("Cummulative product:\n", df.cumprod())
print("Count:\n", df.count())
print("Describe function:\n", df.describe())
